export function expressiveSpeech(dialogue: string, performanceContext: string) {
  const actorDirection = performanceContext.match(/(?:表演|情绪)\s*[:：]\s*([\s\S]*?)(?=；\s*(?:声音|环境声|动作音效)\s*[:：]|$)/)?.[1]?.trim() || performanceContext;
  const intensity = Math.min(5, Math.max(1, Number(actorDirection.match(/(?:强度|intensity)\s*[:：]?\s*([1-5])/i)?.[1] ?? 2)));
  const whispering = /耳语|低声|压低声音|气若游丝|屏息|悄声/.test(actorDirection);
  const weak = /微弱|虚弱|重伤|奄奄一息/.test(actorDirection);
  const angry = /愤怒|暴怒|咆哮|怒吼|质问|仇恨/.test(actorDirection);
  const grieving = /悲伤|失去|绝望|哽咽|悲痛/.test(actorDirection);
  const crying = /哭泣|哭着|落泪|泪流|抽泣/.test(actorDirection);
  const frightened = /惊恐|恐惧|害怕|颤抖/.test(actorDirection);
  const relieved = /松了口气|如释重负|终于安全|得救/.test(actorDirection);
  const chuckling = /轻笑|冷笑|苦笑|笑着说|忍不住笑/.test(actorDirection);
  const cheerful = /开心|兴奋|喜悦|惊喜/.test(actorDirection);
  const shocked = /震惊|惊讶|错愕|不敢相信|猛然发现|倒吸凉气/.test(actorDirection);
  const determined = /坚定|果断|决绝|下定决心|命令|不容置疑|守护/.test(actorDirection);
  const restrained = /冷漠|冰冷|克制|压抑|隐忍|麻木|平静得可怕|面无表情/.test(actorDirection);
  const suspicious = /怀疑|试探|警惕|不确定|疑惑|追问/.test(actorDirection);
  const sarcastic = /讽刺|嘲讽|嘲笑|戏谑|阴阳怪气|挑衅/.test(actorDirection);
  const pleading = /恳求|哀求|祈求|求你|请求|乞求/.test(actorDirection);
  const nervous = /紧张|焦虑|不安|心虚|忐忑|慌张/.test(actorDirection);
  const tender = /温柔|安慰|关切|心疼|深情|宠溺|柔和/.test(actorDirection);
  const excited = /激动|热血|振奋|亢奋|迫不及待/.test(actorDirection);
  const remorseful = /愧疚|后悔|自责|歉意|悔恨/.test(actorDirection);
  const disgusted = /厌恶|嫌弃|鄙夷|不屑|反感/.test(actorDirection);
  const playful = /俏皮|调皮|打趣|逗弄|撒娇/.test(actorDirection);
  const urgent = /急促|大喊|警告|崩溃|紧绷/.test(actorDirection) || /！|!/.test(dialogue);
  const deliberatePause = /停顿|迟疑|犹豫|欲言又止|沉默片刻/.test(actorDirection);
  const instructedSoft = /音量[^；。]*(?:低|轻|小|压低)|轻声|低声|柔声/.test(actorDirection);
  const instructedLoud = /音量[^；。]*(?:高|大|响)|提高音量|大声/.test(actorDirection);

  let paced = dialogue.trim().replace(/……|…+/g, (value) => `${value} [long-pause] `);
  if (deliberatePause && !paced.includes("[pause]")) paced = paced.replace(/([，,；;])/, "$1 [pause] ");

  let text = paced;
  if (whispering) text = `<whisper><soft>${paced}</soft></whisper>`;
  else if (weak) text = `[breath] <slow><soft>${paced}</soft></slow>`;
  else if (angry && intensity >= 4) text = instructedSoft ? `<soft><build-intensity>${paced}</build-intensity></soft>` : `<build-intensity><loud>${paced}</loud></build-intensity>`;
  else if (angry) text = `<emphasis>${paced}</emphasis>`;
  else if (grieving) text = `[sigh] <slow><soft>${paced}</soft></slow>${crying ? " [cry]" : ""}`;
  else if (frightened) text = `[inhale] <higher-pitch>${paced}</higher-pitch>${intensity >= 4 ? " [breath]" : ""}`;
  else if (relieved) text = `[exhale] <soft>${paced}</soft>`;
  else if (chuckling) text = `[chuckle] <laugh-speak>${paced}</laugh-speak>`;
  else if (cheerful) text = `<higher-pitch>${paced}</higher-pitch>`;
  else if (shocked) text = `[inhale] <higher-pitch><emphasis>${paced}</emphasis></higher-pitch>`;
  else if (pleading) text = `<soft><build-intensity>${paced}</build-intensity></soft>`;
  else if (sarcastic) text = `<lower-pitch><emphasis>${paced}</emphasis></lower-pitch>`;
  else if (determined) text = `<lower-pitch><emphasis>${paced}</emphasis></lower-pitch>`;
  else if (restrained) text = `<decrease-intensity><slow>${paced}</slow></decrease-intensity>`;
  else if (suspicious) text = `<slow><soft>${paced}</soft></slow>`;
  else if (remorseful) text = `[sigh] <slow><soft>${paced}</soft></slow>`;
  else if (nervous) text = `[inhale] <soft><higher-pitch>${paced}</higher-pitch></soft>`;
  else if (tender) text = `<soft>${paced}</soft>`;
  else if (excited) text = `<build-intensity><higher-pitch>${paced}</higher-pitch></build-intensity>`;
  else if (disgusted) text = `<lower-pitch><emphasis>${paced}</emphasis></lower-pitch>`;
  else if (playful) text = `<higher-pitch><laugh-speak>${paced}</laugh-speak></higher-pitch>`;
  else if (urgent && intensity >= 4) text = `<build-intensity>${paced}</build-intensity>`;
  else if (urgent) text = `<emphasis>${paced}</emphasis>`;

  const instructedSlow = /语速[^；。]*(?:慢|缓)|缓慢|慢慢/.test(actorDirection);
  const instructedFast = /语速[^；。]*(?:快|急)|快速|急促/.test(actorDirection);
  if (instructedSoft && !/<(?:soft|whisper)>/.test(text)) text = `<soft>${text}</soft>`;
  else if (instructedLoud && !/<(?:loud|soft|whisper)>/.test(text)) text = `<loud>${text}</loud>`;
  if (instructedSlow && !/<slow>/.test(text)) text = `<slow>${text}</slow>`;
  else if (instructedFast && !/<(?:fast|slow)>/.test(text)) text = `<fast>${text}</fast>`;
  const naturalSpeed = instructedSlow ? 0.9 : instructedFast ? 1.08 : grieving || weak || remorseful ? 0.9 : restrained ? 0.91 : whispering || suspicious || tender ? 0.94 : pleading || nervous ? 0.96 : shocked ? 1.03 : excited ? 1.07 : playful ? 1.04 : angry || urgent ? 1 + intensity * 0.012 : 0.98;
  return { text, speed: Math.min(1.2, Math.max(0.78, naturalSpeed)) };
}
