"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useEffect, useMemo, useRef, useState } from "react";
import { supabase } from "@/app/lib/supabase";

type Shot = { id:string; shot_number:number; duration_seconds:number; scene:string; dialogue:string; image_url?:string; video_url?:string; source_video_url?:string|null; audio_url?:string; voice_id?:string; media_status?:string; speaker_character_id?:string|null; subtitle_start_ms?:number; subtitle_end_ms?:number };
type Project = { id:string; title:string; created_at:string; storyboard_shots:Shot[] };
type CaptionCue = { text:string; start:number; end:number };

function hasEmbeddedVoice(item: Shot) { return item.media_status === "lipsync_ready" || /heygen/i.test(item.video_url || ""); }
function requiresLipSync(item: Shot) { return Boolean(item.dialogue?.trim()&&item.speaker_character_id); }
function srtTime(seconds:number) { const ms=Math.max(0,Math.round(seconds*1000));const hours=Math.floor(ms/3600000);const minutes=Math.floor(ms%3600000/60000);const secs=Math.floor(ms%60000/1000);return `${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(secs).padStart(2,"0")},${String(ms%1000).padStart(3,"0")}`; }
function fallbackCaptionCues(text:string,duration:number){const value=text.trim();if(!value)return[];const segments:string[]=[];let chunk="";let spoken=0;for(const char of Array.from(value)){chunk+=char;if(!/[\s，。！？、…,.!?]/.test(char))spoken++;if(/[。！？!?]/.test(char)||spoken>=12){segments.push(chunk.trim());chunk="";spoken=0;}}if(chunk.trim())segments.push(chunk.trim());const weights=segments.map((segment)=>Math.max(1,Array.from(segment.replace(/[\s，。！？、…,.!?]/g,"")).length));const total=weights.reduce((sum,item)=>sum+item,0);let cursor=0;return segments.map((segment,index)=>{const start=cursor;cursor=index===segments.length-1?duration:Math.min(duration,cursor+duration*weights[index]/total);return{text:segment,start,end:cursor};}).filter((cue)=>cue.end>cue.start);}

async function subtitleOverlay(text:string) {
  const canvas=document.createElement("canvas"); canvas.width=720; canvas.height=1280; const context=canvas.getContext("2d"); if(!context) throw new Error("浏览器无法创建字幕画布");
  context.clearRect(0,0,720,1280); if(text.trim()) { context.font='700 34px "Microsoft YaHei","PingFang SC",sans-serif'; context.textAlign="center"; context.textBaseline="middle"; context.lineJoin="round"; context.lineWidth=9; context.strokeStyle="rgba(0,0,0,.88)"; context.fillStyle="white";
    const chars=Array.from(text.trim()); const lines:string[]=[]; let line=""; for(const char of chars){const next=line+char;if(context.measureText(next).width>620&&line){lines.push(line);line=char;}else line=next;}if(line)lines.push(line); const visible=lines.slice(0,3); const start=1110-(visible.length-1)*25; visible.forEach((item,index)=>{const y=start+index*50;context.strokeText(item,360,y);context.fillText(item,360,y);}); }
  return await new Promise<Blob>((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("字幕画面生成失败")),"image/png"));
}

export default function EpisodePage() {
  const params = useParams<{ id:string }>(); const router = useRouter();
  const [project,setProject] = useState<Project|null>(null); const [index,setIndex] = useState(0); const [playing,setPlaying] = useState(false); const [elapsed,setElapsed] = useState(0); const [error,setError] = useState(""); const [exporting,setExporting]=useState(false); const [exportProgress,setExportProgress]=useState(0); const [exportStatus,setExportStatus]=useState(""); const [mediaDurations,setMediaDurations]=useState<Record<string,number>>({}); const [captionTracks,setCaptionTracks]=useState<Record<string,CaptionCue[]>>({});
  const videoRef = useRef<HTMLVideoElement>(null); const audioRef = useRef<HTMLAudioElement>(null);
  const shots = useMemo(() => project?.storyboard_shots ?? [], [project]); const shot = shots[index];
  const subtitleDuration = (item: Shot) => { const timed = Number(item.subtitle_end_ms ?? 0) - Number(item.subtitle_start_ms ?? 0); return timed > 0 ? Math.min(mediaDurations[item.id] ?? item.duration_seconds, timed / 1000) : mediaDurations[item.id] ?? item.duration_seconds; };
  const captionsFor=(item:Shot)=>captionTracks[item.id]?.length?captionTracks[item.id]:fallbackCaptionCues(item.dialogue,subtitleDuration(item));
  const total = useMemo(() => shots.reduce((sum,item)=>sum+(mediaDurations[item.id]??item.duration_seconds),0),[shots,mediaDurations]);
  const before = useMemo(() => shots.slice(0,index).reduce((sum,item)=>sum+(mediaDurations[item.id]??item.duration_seconds),0),[shots,index,mediaDurations]);
  const companionAudio = shot ? hasEmbeddedVoice(shot) ? shot.source_video_url : shot.audio_url : undefined;
  const visibleSubtitle = shot ? (!playing ? shot.dialogue : captionsFor(shot).find((cue)=>elapsed>=cue.start&&elapsed<=cue.end+.08)?.text || "") : "";
  const missingVisualCount=shots.filter((item)=>!item.video_url&&!item.image_url).length;
  const missingVoiceCount=shots.filter((item)=>item.dialogue?.trim()&&!item.audio_url).length;
  const unsyncedVoiceCount=shots.filter((item)=>requiresLipSync(item)&&(!item.video_url||!hasEmbeddedVoice(item))).length;
  const episodeReady=shots.length>0&&missingVisualCount===0&&missingVoiceCount===0&&unsyncedVoiceCount===0;

  useEffect(() => { supabase.auth.getUser().then(async ({data}) => { if(!data.user){router.replace("/login");return;} const response=await fetch(`/api/storyboard/projects/${params.id}?includeSources=1`,{cache:"no-store"}); const body=await response.json(); if(!response.ok){setError(body.error);return;} setProject(body.project); }); },[params.id,router]);
  useEffect(() => { const probes=shots.filter((item)=>item.video_url&&!mediaDurations[item.id]).map((item)=>{const video=document.createElement("video");video.preload="metadata";video.onloadedmetadata=()=>{if(Number.isFinite(video.duration)&&video.duration>0)setMediaDurations((current)=>({...current,[item.id]:video.duration}));};video.src=item.video_url!;return video;});return()=>probes.forEach((video)=>{video.removeAttribute("src");video.load();});},[shots,mediaDurations]);
  useEffect(() => { const media:HTMLMediaElement[]=[];for(const item of shots.slice(index+1,index+3)){if(item.video_url){const video=document.createElement("video");video.preload="auto";video.src=item.video_url;video.load();media.push(video);}const audio=hasEmbeddedVoice(item)?item.source_video_url:item.audio_url;if(audio){const element=document.createElement("audio");element.preload="auto";element.src=audio;element.load();media.push(element);}}return()=>media.forEach((element)=>{element.removeAttribute("src");element.load();});},[shots,index]);
  useEffect(() => { let active=true;Promise.all(shots.filter((item)=>item.audio_url).map(async(item)=>{try{const timingsUrl=item.audio_url!.replace(/\.mp3(?:\?.*)?$/,".timings.json");const response=await fetch(`/api/media?url=${encodeURIComponent(timingsUrl)}`,{cache:"no-store"});if(!response.ok)return;const data=await response.json() as {cues?:CaptionCue[]};if(active&&data.cues?.length)setCaptionTracks((current)=>({...current,[item.id]:data.cues!}));}catch{}}));return()=>{active=false;};},[shots]);
  useEffect(() => {
    if(!playing || !shot) return;
    const video=videoRef.current;const audio=audioRef.current;const duration=mediaDurations[shot.id]??shot.duration_seconds;const started=performance.now();let frame=0;let finished=false;
    video?.play().catch(()=>undefined);audio?.play().catch(()=>undefined);
    const tick=()=>{if(finished)return;const fallback=(performance.now()-started)/1000;const clock=audio&&!audio.paused?audio.currentTime:video&&!video.paused?video.currentTime:fallback;if(audio&&video&&Math.abs(video.currentTime-audio.currentTime)>.08)video.currentTime=Math.min(audio.currentTime,Math.max(0,video.duration||duration));setElapsed(Math.min(clock,duration));if(clock>=duration-.03){finished=true;if(index<shots.length-1){setElapsed(0);setIndex((value)=>value+1);}else setPlaying(false);return;}frame=requestAnimationFrame(tick);};
    frame=requestAnimationFrame(tick);return()=>{finished=true;cancelAnimationFrame(frame);};
  },[playing,index,shot,shots.length,mediaDurations]);
  useEffect(() => { if(videoRef.current) videoRef.current.volume=shot&&hasEmbeddedVoice(shot)?1:shot?.audio_url?0.2:1;if(audioRef.current)audioRef.current.volume=shot&&hasEmbeddedVoice(shot)?0.16:1; },[shot]);

  function toggle(){ if(!shot)return; if(playing){videoRef.current?.pause();audioRef.current?.pause();setPlaying(false);} else setPlaying(true); }
  function selectShot(next:number){ setElapsed(0); setIndex(Math.min(shots.length-1,Math.max(0,next))); }
  function downloadManifest(){ if(!project)return; const timeline=shots.map((item,i)=>{const start=shots.slice(0,i).reduce((sum,s)=>sum+(mediaDurations[s.id]??s.duration_seconds),0);const duration=mediaDurations[item.id]??item.duration_seconds;const cues=captionsFor(item);return {order:i+1,start_seconds:start,duration_seconds:duration,video:item.video_url??null,image:item.image_url??null,audio:item.audio_url??null,subtitle:item.dialogue??"",caption_cues:cues.map((cue)=>({text:cue.text,start_seconds:start+cue.start,end_seconds:start+Math.min(duration,cue.end),local_start_seconds:cue.start,local_end_seconds:Math.min(duration,cue.end)}))};}); const url=URL.createObjectURL(new Blob([JSON.stringify({project:{id:project.id,title:project.title},format:"9:16",timeline},null,2)],{type:"application/json"})); const a=document.createElement("a");a.href=url;a.download=`${project.title}-剪辑工程.json`;a.click();URL.revokeObjectURL(url); }
  function downloadSrt(){ if(!project)return;let offset=0;let sequence=1;const blocks:string[]=[];for(const item of shots){const duration=mediaDurations[item.id]??item.duration_seconds;const cues=captionsFor(item);for(const cue of cues){const start=offset+Math.max(0,Math.min(duration,cue.start));const end=offset+Math.max(0,Math.min(duration,cue.end));if(cue.text.trim()&&end>start)blocks.push(`${sequence++}\n${srtTime(start)} --> ${srtTime(end)}\n${cue.text.trim()}`);}offset+=duration;}const url=URL.createObjectURL(new Blob([`\uFEFF${blocks.join("\n\n")}\n`],{type:"application/x-subrip;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`${project.title}-精准字幕.srt`;a.click();URL.revokeObjectURL(url);setExportStatus(`已导出 ${blocks.length} 条精准字幕`);}

  async function exportMp4(){ if(!project||exporting)return; const missing=shots.filter((item)=>!item.video_url&&!item.image_url); if(missing.length)return setExportStatus(`还有 ${missing.length} 个镜头没有画面，请先完成整集生成`);
    const missingVoices=shots.filter((item)=>item.dialogue?.trim()&&!item.audio_url);if(missingVoices.length)return setExportStatus(`还有 ${missingVoices.length} 个对白镜头没有配音，已暂停导出`);
    const unsyncedVoices=shots.filter((item)=>requiresLipSync(item)&&(!item.video_url||!hasEmbeddedVoice(item)));if(unsyncedVoices.length)return setExportStatus(`还有 ${unsyncedVoices.length} 个角色对白镜头没有完成说话视频和口型同步，已暂停导出`);
    setExporting(true);setExportProgress(0);setExportStatus("正在加载本地视频渲染器…");let renderer:{terminate:()=>void}|null=null;
    try { const [{FFmpeg},{fetchFile,toBlobURL}]=await Promise.all([import("@ffmpeg/ffmpeg"),import("@ffmpeg/util")]); const ffmpeg=new FFmpeg();renderer=ffmpeg; ffmpeg.on("progress",({progress})=>setExportProgress(Math.max(1,Math.min(99,Math.round(progress*100))))); await ffmpeg.load({coreURL:await toBlobURL("/render-engine/engine","text/javascript"),wasmURL:await toBlobURL("/render-engine/data","application/wasm")}); const segmentNames:string[]=[];
      const fetchWithRetry=async(url:string,label:string)=>{let failure:unknown;for(let attempt=1;attempt<=3;attempt++){try{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error(`${label} 读取失败（${response.status}）`);return new Uint8Array(await response.arrayBuffer());}catch(error){failure=error;if(attempt<3){setExportStatus(`${label} 读取失败，正在重试 ${attempt}/2…`);await new Promise((resolve)=>setTimeout(resolve,700*attempt));}}}throw failure instanceof Error?failure:new Error(`${label} 读取失败`);};
      for(let i=0;i<shots.length;i++){
        const item=shots[i];const duration=String(Math.max(2,mediaDurations[item.id]??item.duration_seconds));const fadeOut=Math.max(0,Number(duration)-0.12).toFixed(3);const captionDuration=subtitleDuration(item).toFixed(3);const firstShot=i===0;const lastShot=i===shots.length-1;const videoFades=`${firstShot?",fade=t=in:st=0:d=.12":""}${lastShot?`,fade=t=out:st=${fadeOut}:d=.12`:""}`;const audioFades=`,afade=t=in:st=0:d=.04,afade=t=out:st=${fadeOut}:d=.08`;
        setExportStatus(`正在渲染镜头 ${i+1}/${shots.length}…`);setExportProgress(Math.round(i/shots.length*90));
        const visual=item.video_url||item.image_url!;const sourceName=`visual-${i}.${item.video_url?"mp4":"img"}`;const audioName=`audio-${i}.mp3`;const ambientName=`ambient-${i}.mp4`;const segmentName=`segment-${i}.mp4`;const proxy=(url:string)=>`/api/media?url=${encodeURIComponent(url)}`;const separateVoice=Boolean(item.audio_url&&!hasEmbeddedVoice(item));const sourceAmbience=Boolean(item.source_video_url&&hasEmbeddedVoice(item));
        const captionCues=captionsFor(item).filter((cue)=>cue.text&&cue.end>cue.start&&cue.start<Number(captionDuration)).map((cue)=>({...cue,end:Math.min(cue.end,Number(captionDuration))}));const subtitleNames=captionCues.map((_,cueIndex)=>`subtitle-${i}-${cueIndex}.png`);
        await ffmpeg.writeFile(sourceName,await fetchWithRetry(proxy(visual),`镜头 ${item.shot_number} 画面`));if(separateVoice)await ffmpeg.writeFile(audioName,await fetchWithRetry(proxy(item.audio_url!),`镜头 ${item.shot_number} 配音`));if(sourceAmbience)await ffmpeg.writeFile(ambientName,await fetchWithRetry(proxy(item.source_video_url!),`镜头 ${item.shot_number} 环境声`));for(let cueIndex=0;cueIndex<captionCues.length;cueIndex++)await ffmpeg.writeFile(subtitleNames[cueIndex],await fetchFile(await subtitleOverlay(captionCues[cueIndex].text)));
        const sourceArgs=item.video_url?["-i",sourceName]:["-loop","1","-framerate","30","-t",duration,"-i",sourceName];const audioArgs=separateVoice?["-i",audioName]:sourceAmbience?["-i",ambientName]:["-f","lavfi","-t",duration,"-i","anullsrc=channel_layout=stereo:sample_rate=44100"];
        const subtitleArgs=subtitleNames.flatMap((name)=>["-loop","1","-i",name]);let subtitleChain="";let priorLabel="base";captionCues.forEach((cue,cueIndex)=>{const nextLabel=cueIndex===captionCues.length-1?"v":`caption${cueIndex}`;subtitleChain+=`;[${priorLabel}][${cueIndex+2}:v]overlay=0:0:format=auto:enable='between(t,${Math.max(0,cue.start).toFixed(3)},${Math.min(Number(duration),cue.end+.08).toFixed(3)})'[${nextLabel}]`;priorLabel=nextLabel;});if(!captionCues.length)subtitleChain=";[base]null[v]";
        const videoFilter=`[0:v]scale=720:1280:force_original_aspect_ratio=decrease,pad=720:1280:(ow-iw)/2:(oh-ih)/2:black,setsar=1,tpad=stop_mode=clone:stop_duration=${duration}${videoFades}[base]${subtitleChain}`;
        const baseVoiceFilter=separateVoice?`volume=2,loudnorm=I=-16:TP=-1.5:LRA=11,apad`:`apad`;const voiceFilter=`${baseVoiceFilter}${audioFades}`;
        const commonArgs=["-t",duration,"-r","30","-c:v","libx264","-preset","veryfast","-crf","23","-pix_fmt","yuv420p","-c:a","aac","-b:a","192k","-ar","44100","-ac","2","-movflags","+faststart",segmentName];
        let rendered=false;
        if(item.video_url){
          const mixedAudio=separateVoice?`[0:a]volume=.18,aresample=44100,apad[amb];[1:a]${baseVoiceFilter}[voice];[amb][voice]amix=inputs=2:duration=longest:dropout_transition=0${audioFades}[a]`:sourceAmbience?`[0:a]volume=.95,aresample=44100,apad[voice];[1:a]volume=.16,aresample=44100,apad[amb];[voice][amb]amix=inputs=2:duration=longest:dropout_transition=0${audioFades}[a]`:`[0:a]volume=.85,aresample=44100,apad${audioFades}[a]`;
          const mixedExit=await ffmpeg.exec([...sourceArgs,...audioArgs,...subtitleArgs,"-filter_complex",`${videoFilter};${mixedAudio}`,"-map","[v]","-map","[a]",...commonArgs]);rendered=mixedExit===0;
          if(!rendered) await ffmpeg.deleteFile(segmentName).catch(()=>undefined);
        }
        if(!rendered){const fallbackAudio=sourceAmbience?"0:a":"1:a";const fallbackExit=await ffmpeg.exec([...sourceArgs,...audioArgs,...subtitleArgs,"-filter_complex",videoFilter,"-map","[v]","-map",fallbackAudio,"-af",voiceFilter,...commonArgs]);if(fallbackExit!==0)throw new Error(`镜头 ${item.shot_number} 音视频渲染失败`);}
        segmentNames.push(segmentName);
        for(const temporary of [sourceName,...(separateVoice?[audioName]:[]),...(sourceAmbience?[ambientName]:[]),...subtitleNames])await ffmpeg.deleteFile(temporary).catch(()=>undefined);
      }
      await ffmpeg.writeFile("segments.txt",segmentNames.map((name)=>`file '${name}'`).join("\n"));setExportStatus("正在合并整集并封装 MP4…");setExportProgress(95);
      const concatExit=await ffmpeg.exec(["-f","concat","-safe","0","-i","segments.txt","-c","copy","-movflags","+faststart","episode.mp4"]);if(concatExit!==0)throw new Error("整集镜头合并失败");
      const output=await ffmpeg.readFile("episode.mp4");if(typeof output==="string"||output.byteLength<1024)throw new Error("视频编码结果为空或异常");
      for(const name of [...segmentNames,"segments.txt","episode.mp4"])await ffmpeg.deleteFile(name).catch(()=>undefined);
      const url=URL.createObjectURL(new Blob([output as Uint8Array<ArrayBuffer>],{type:"video/mp4"}));const link=document.createElement("a");link.href=url;link.download=`${project.title}-影动AI.mp4`;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),30000);setExportProgress(100);setExportStatus("整集 MP4 已导出到下载文件夹");
    }catch(reason){setExportStatus(reason instanceof Error?`导出失败：${reason.message}`:"整集导出失败，请重试");}finally{renderer?.terminate();setExporting(false);}}

  if(error)return <main className="episode-page"><div className="episode-empty">{error}<Link href={`/storyboard?project=${params.id}`}>返回分镜</Link></div></main>;
  if(!project||!shot)return <main className="episode-page"><div className="episode-empty">正在加载整集时间轴…</div></main>;
  return <main className="episode-page">
    <header className="admin-head"><Link className="wordmark" href="/"><span>影</span><b>影动 AI</b></Link><Link href={`/storyboard?project=${params.id}`}>返回分镜</Link></header>
    <section className="episode-editor">
      <div className="episode-stage">
        <div className="episode-phone">{shot.video_url ? <video className="episode-visual" key={shot.id} ref={videoRef} src={shot.video_url} preload="auto" playsInline/> : shot.image_url ? <Image className="episode-visual" key={shot.id} src={shot.image_url} alt={shot.scene} fill unoptimized/> : <div className="episode-placeholder">镜头 {shot.shot_number}<small>{shot.scene}</small></div>}{companionAudio&&<audio ref={audioRef} src={companionAudio} preload="auto"/>} {visibleSubtitle&&<div className="episode-subtitle" key={`subtitle-${shot.id}-${visibleSubtitle}`}>{visibleSubtitle}</div>}</div>
        <div className="episode-controls"><button onClick={()=>selectShot(index-1)}>上一镜</button><button className="episode-play" onClick={toggle}>{playing?"暂停":"播放整集"}</button><button onClick={()=>selectShot(index+1)}>下一镜</button></div>
      </div>
      <div className="episode-panel"><p className="eyebrow">AUTO EDIT TIMELINE</p><h1>{project.title}</h1><p>视频、配音与字幕已按镜头顺序自动排列。</p><div className={`episode-readiness ${episodeReady?"ready":"needs-work"}`}><b>{episodeReady?"整集已就绪":"整集还需完善"}</b><span>{missingVisualCount>0?`缺 ${missingVisualCount} 个画面`:"画面完整"}</span><span>{missingVoiceCount>0?`缺 ${missingVoiceCount} 段配音`:"配音完整"}</span><span>{unsyncedVoiceCount>0?`${unsyncedVoiceCount} 个镜头未对口型`:"口型同步完成"}</span></div><div className="episode-summary"><b>{shots.length} 镜</b><b>{total.toFixed(1)} 秒</b><b>{shots.filter(item=>item.video_url).length} 段视频</b><b>{shots.filter(item=>item.audio_url).length} 段配音</b></div><div className="episode-progress"><i style={{width:`${Math.min(100,(before+elapsed)/Math.max(total,1)*100)}%`}}/></div><div className="episode-timeline">{shots.map((item,i)=>{const duration=mediaDurations[item.id]??item.duration_seconds;return <button className={i===index?"active":""} key={item.id} onClick={()=>selectShot(i)} style={{flexGrow:duration}}><b>{String(item.shot_number).padStart(2,"0")}</b><small>{duration.toFixed(1)}s</small><span>{item.video_url?"视频":"图片"}{item.audio_url?" + 配音":""}</span></button>;})}</div><div className="episode-export-actions"><button className="episode-export" disabled={exporting} onClick={()=>void exportMp4()}>{exporting?"正在渲染 MP4…":"自动剪辑并导出 MP4"}</button><button onClick={downloadSrt}>导出精准 SRT</button><button onClick={downloadManifest}>导出剪辑工程 JSON</button></div>{(exporting||exportProgress>0)&&<div className="episode-render-progress"><i style={{width:`${exportProgress}%`}}/></div>}{exportStatus&&<small className="episode-note">{exportStatus}</small>}<small className="episode-note">MP4 在当前电脑本地渲染，不额外消耗生成积分。导出时请保持页面打开。</small></div>
    </section>
  </main>;
}
